import requests
import json
from datetime import datetime

def scrape_shungo_spawns():
    print("🚀 Fetching spawns from Shungo API...")
    
    # 1. Get the raw spawn data from Shungo API
    api_url = "https://shungo.app/api/shungo/data/spawns"
    response = requests.get(api_url)
    data = response.json()
    result_array = data["result"]
    
    print(f"📊 Raw spawns: {len(result_array)} entries")
    
    # 2. Get the form mappings from the JSON file (generated by your Playwright script)
    try:
        with open('shungo_forms.json', 'r') as f:
            forms_data = json.load(f)
            form_mappings = forms_data.get("form_mappings", {})
        print(f"📋 Loaded form mappings for {len(form_mappings)} Pokémon")
    except FileNotFoundError:
        print("⚠️ shungo_forms.json not found, using no form mappings")
        form_mappings = {}
    
    # 3. Combine them
    spawns = []
    form_map = {}
    
    # Convert form_mappings to use int keys and float rates
    for id_str, rates in form_mappings.items():
        pokemon_id = int(id_str)
        form_map[pokemon_id] = {}
        for rate_str, name in rates.items():
            rate = float(rate_str)
            form_map[pokemon_id][rate] = name
    
    for item in result_array:
        pokemon_id = item[0]
        rate = item[2]
        is_shiny = item[3] == "true" or item[3] == True
        
        # Get base name
        base_name = get_pokemon_name(pokemon_id)
        
        # Try to find form name from mapping
        form_name = base_name
        if pokemon_id in form_map:
            # Find closest rate match
            closest_rate = None
            closest_diff = 1.0
            for map_rate in form_map[pokemon_id].keys():
                diff = abs(map_rate - rate)
                if diff < closest_diff:
                    closest_diff = diff
                    closest_rate = map_rate
            if closest_rate and closest_diff < 0.05:
                form_name = form_map[pokemon_id][closest_rate]
        
        spawns.append({
            "id": pokemon_id,
            "name": form_name,
            "rate": round(rate, 2),
            "shiny": is_shiny
        })
    
    # 4. Save to JSON
    output = {
        "last_updated": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "total": len(spawns),
        "spawns": spawns
    }
    
    with open('spawns.json', 'w') as f:
        json.dump(output, f, indent=2)
    
    print(f"\n💾 Saved to spawns.json")
    print(f"   Total spawns: {len(spawns)}")
    print(f"   Last updated: {output['last_updated']}")

def get_pokemon_name(pokemon_id):
    # Simple mapping for common Pokémon (you can expand this)
    names = {
        351: "Castform",
        742: "Cutiefly",
        829: "Gossifleur",
        273: "Seedot",
        688: "Binacle",
        590: "Foongus",
        948: "Toedscool",
        540: "Sewaddle",
        506: "Lillipup",
        539: "Sawk",
        10: "Caterpie",
        813: "Scorbunny",
        631: "Heatmor",
        543: "Venipede",
        843: "Silicobra",
        632: "Durant",
        538: "Throh",
        43: "Oddish",
        338: "Solrock"
    }
    return names.get(pokemon_id, f"Pokemon #{pokemon_id}")

if __name__ == "__main__":
    scrape_shungo_spawns()